[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
altv = { features = ["clientside"], path = "../../../altv-rust/altv"}
# TODO: make it workspace dependency
serde = { version = "=1.0.203", features = ["derive"] }
bincode = "=1.3.3"

[lib]
crate-type = ["cdylib"]
